name: pgactive CI

on:
  #schedule:
  #  # Runs every day at 5am.
  #  - cron:  '0 5 * * *'
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - id: set-versions
        run: |
          curl -s https://www.postgresql.org/versions.json > versions.json
          # Format as JSON array and map 'major' to 'REL_XX_STABLE' for postgres branch checkout
          VERSIONS=$(jq -c '[.[] | select(.supported == true) | "REL_" + (.major | tostring) + "_STABLE"]' versions.json)
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT

  test:
    needs: setup-matrix
    defaults:
      run:
        shell: sh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: ${{ fromJson(needs.setup-matrix.outputs.versions) }}
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
      - name: Checkout pgactive
        uses: actions/checkout@v4
        with:
          path: pgactive

      - name: Checkout Postgres
        run: |
          sudo apt-get -y -q install libipc-run-perl build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config libicu-dev
          git clone --depth 1 --branch ${{ matrix.version }} https://github.com/postgres/postgres.git

      - if: ${{ matrix.version == 'REL_11_STABLE' }}
        name: Apply per-test-script runtime display patch (REL_11_STABLE only)
        run: |
          cd postgres
          git apply $GITHUB_WORKSPACE/pgactive/src/compat/11/v1-0001-Add-per-test-script-runtime-display-to-pg_regress.patch
          git status

      - name: Build Postgres
        run: |
          cd postgres
          sh configure --prefix=$PWD/inst/ --enable-debug --enable-cassert --enable-tap-tests CFLAGS="-ggdb3 -O0"
          make -j4 install
          # Install extensions required for pgactive tests
          make -C contrib/btree_gist install
          make -C contrib/cube install
          make -C contrib/hstore install
          make -C contrib/pg_trgm install

      - if: ${{ matrix.version == 'REL_17_STABLE' }}
        name: Check pgactive code indentation (REL_17_STABLE only)
        run: |
          cd postgres
          make -C src/tools/pg_bsd_indent/ -j4 install
          cat << EOF >> pgindent.ignore
          src/compat/13/pg_dump/*
          src/compat/14/pg_dump/*
          src/compat/15/pg_dump/*
          src/compat/16/pg_dump/*
          src/compat/17/pg_dump/*
          src/compat/18/pg_dump/*
          EOF
          src/tools/pgindent/pgindent --indent=$GITHUB_WORKSPACE/postgres/src/tools/pg_bsd_indent/pg_bsd_indent --excludes=pgindent.ignore --diff $GITHUB_WORKSPACE/pgactive > pgindent.diffs
          test -s pgindent.diffs && cat pgindent.diffs && exit 1 || exit 0

      - name: Build pgactive
        run: |
          cd pgactive
          PATH=$GITHUB_WORKSPACE/postgres/inst/bin:"$PATH" sh configure
          make PROFILE="-Wall -Wmissing-prototypes -Werror=maybe-uninitialized -Werror" -j1 all install

      - name: Run pgactive core tests
        run: |
          cd pgactive
          make regress_check

      - name: Show pgactive core tests diff
        if: ${{ failure() }}
        run: |
          cat pgactive/test/regression.diffs

      - name: Run pgactive extended tests
        run: |
          cd pgactive
          make PROVE_FLAGS="--timer -v" prove_check

      - name: Upload test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact-${{ matrix.os }}-${{ matrix.version }}
          path: |
            postgres/pgindent.diffs
            pgactive/test/regression.diffs
            pgactive/test/tmp_check/log
          retention-days: 1
